### ISSUE TITLE
No support for custom fields

### ISSUE THREAD

**Issue by jfu334** [MoshiBin/ssdpy#52]
SSDP allows custom fields to be send by the server. However ssdpy does not support them. 

See https://web.archive.org/web/20150905102426/http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf chapter 1.1.3, SSDP header field extensions.

**Comment by MoshiBin** [comment]
Very good point. I'll add support for custom fields in both the Python API and the ssdpy-server CLI.

**Comment by MoshiBin** [comment]
You can now provide custom fields in several ways:
* From the CLI:
```bash
$ ssdpy-server -e myheader.philips.com "some value" -e myheader.sony.com "other value"
```
* From Python:
```python
server = SSDPServer("test-server", extra_fields={
    "myheader.philips.com": "some value",
    "myheader.sony.com": "other value",
})
```

This has been rolled into version 0.4.0.
